from __future__ import annotations

from typing import Any

from shopping_agent.domain.schemas import Constraint
from shopping_agent.ranking.precise_features import build_global_idf, extract_batch_features

# Fitted from data, not hand-picked. Generated by
# scripts/fit_precise_reranker_weights.py: an unconstrained, class-balanced
# logistic regression over the same 13 features FallbackReranker/PreciseReranker
# already compute, trained on evaluator/local_evaluator.py sessions built from
# data/public_set.jsonl[100:200] (target parent_asin = positive label), and
# validated on the disjoint [0:100] holdout -- TechnicalScore 0.642464 vs
# FallbackReranker's 0.634392 on that same holdout (a real, if modest, win; see
# docs/precise_reranker_change_report.md section 10 for the full methodology,
# including a sign-constrained variant that was tried and performed *worse*
# than this unconstrained fit -- 0.566 -- so it was not used).
#
# Caveat: exact_matches and partial_matches came out negative and budget_penalty
# came out ~0. That is very likely multicollinearity (rrf_raw/attribute_raw/
# quality already carry overlapping signal) rather than "exact constraint
# matches genuinely hurt" -- these are only 100 training sessions (~306 positive
# rows out of 180k), so the coefficients are not fully stable yet. Retrain with
# more sessions (or full k-fold CV) before trusting the exact magnitudes; treat
# this as "beats the hand-tuned baseline on held-out data today", not as a
# finished, interpretable model.
DEFAULT_WEIGHTS: dict[str, float] = {
    "exact_matches": -0.5059620374702732,
    "partial_matches": -16.319593300125614,
    "category_match": 1.1545720987697576,
    "term_coverage": 3.1478954332186824,
    "lexical_signal": 5.583730290442667,
    "rrf_raw": 60.50718504951105,
    "dense_raw": -2.785817996711811,
    "attribute_raw": 0.48373242928076143,
    "profile_match": 0.9653461568603957,
    "quality": 21.904037688336764,
    "contradictions": -4.186928093131388,
    "budget_penalty": 0.0,
    "novelty_penalty": -1.5694228370472272,
}


class PreciseReranker:
    """Feature-scored precise ranker.

    Same CandidateRanker contract as FallbackReranker. Adds: bayesian-shrunk
    quality (average_rating x rating_number instead of rating_number alone),
    explicit soft-constraint contradiction detection (material/color/style/
    use_case/brand, not just budget), and a continuous budget penalty instead
    of a flat one. Recall-signal handling (rrf/dense/attribute/lexical) and
    term coverage intentionally mirror FallbackReranker's scale -- see
    docs/precise_reranker_change_report.md for why an earlier normalized/
    batch-idf version regressed and was reverted.

    Pass `catalog_products` (a CatalogIndex.products-shaped dict) once at
    construction to enable proper corpus-wide idf weighting for term_coverage
    / profile_match; without it, term coverage falls back to a plain overlap
    ratio (same as FallbackReranker), which is still correct, just less
    precise about which terms are actually rare.
    """

    def __init__(
        self,
        weights: dict[str, float] | None = None,
        catalog_products: dict[str, dict[str, Any]] | None = None,
    ) -> None:
        self.weights = {**DEFAULT_WEIGHTS, **(weights or {})}
        self.idf = build_global_idf(catalog_products) if catalog_products else None

    def rank(
        self,
        candidates: list[dict[str, Any]],
        *,
        query: str,
        category: str,
        constraints: list[Constraint],
        profile: dict[str, Any] | None = None,
        previously_recommended: set[str] | None = None,
    ) -> list[dict[str, Any]]:
        if not candidates:
            return []

        features = extract_batch_features(
            candidates,
            query=query,
            category=category,
            constraints=constraints,
            profile=profile,
            previously_recommended=previously_recommended,
            idf=self.idf,
        )

        w = self.weights
        ranked: list[dict[str, Any]] = []
        for candidate, feat in zip(candidates, features):
            score = (
                w["exact_matches"] * feat.exact_matches
                + w["partial_matches"] * feat.partial_matches
                + w["category_match"] * feat.category_match
                + w["term_coverage"] * feat.term_coverage
                + w["lexical_signal"] * feat.lexical_signal
                + w["rrf_raw"] * feat.rrf_raw
                + w["dense_raw"] * feat.dense_raw
                + w["attribute_raw"] * feat.attribute_raw
                + w["profile_match"] * feat.profile_match
                + w["quality"] * feat.quality
                + w["contradictions"] * feat.contradictions
                + w["budget_penalty"] * feat.budget_penalty
                + w["novelty_penalty"] * feat.novelty_penalty
            )
            ranked.append({
                **candidate,
                "reranker_score": score,
                "reranker_explanation": feat.explanations,
            })

        ranked.sort(
            key=lambda item: (
                -float(item["reranker_score"]),
                int(item.get("lexical_rank") or 999999),
            )
        )
        return ranked
